version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      # Install Ruby dependencies from the Gemfile.
      - bundle  install

  build:
    commands:
      # Run the tests using RSpec.
      - rspec