version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      # Install Ruby dependencies from the Gemfile.
      - bundle install --path vendor/bundle

  build:
    commands:
      # Run the tests using RSpec.
      - bundle exec rspec spec/
